### PR TITLE
Update to newest version.

### PR DESCRIPTION
**Pull request by mrstegeman**

### CODE REVIEW

**Comment by pschmitt** [comment]
Thanks, wanna adopt it? I'm no longer using Pagekite.

**Comment by mrstegeman** [comment]
Yes, I'll happily adopt it.

**Comment by pschmitt** [comment]
Great. What's your nick on the AUR?

**Comment by mrstegeman** [comment]
mrstegeman

**Comment by pschmitt** [comment]
Stupid me. I don't need your nick. I forgot that I can just disown a package :man_facepalming: 
It's orphaned now, go pick it up! https://aur.archlinux.org/packages/pagekite/

**Comment by mrstegeman** [comment]
Done, thank you!

**Comment by pschmitt** [comment]
Do you want to keep this GitHub mirror active? If yes, I'll add you here as a collaborator. Otherwise I'll just archive this repo.

**Comment by mrstegeman** [comment]
Feel free to archive. I'll just keep my repo as a proper fork of yours.

**Pull request merged**
